line-length = 120
target-version = "py311"

[lint]
select = [
    "E402",
    "E",    # Pycodestyle errors
    "F",    # Pyflakes
    "I",    # Import sorting
    "UP",   # pyupgrade
]

[lint.isort]
known-first-party = ["backend"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
